### ISSUE TITLE
Pypi package

### ISSUE THREAD

**Issue by LucBerge** [DiegoVicen/som-tsp#11]
Hey @diego-vicente,
It would be nice to have a Pypi package for your algorithm.

We could be able to solve a TSP problem with the following command `som-tsp myfile.tsp`.

With some options I could choose whether to output the brut path, print the logs, display the distance, plot a graph or an animation...etc

**Comment by diego-vicente** [comment]
This is currently not in the roadmap since it seems like a lot of functionality is missing and, in case I were to tackle pending work, I would try to start with much smaller tasks regarding the module. Feel free to fork if you need to

**Comment by LucBerge** [comment]
I just need to access the `route` variable in the main function. The only option I currently have to embeed your algorithm in my software is to create another `main.py` that returns the values I need.

**Comment by diego-vicente** [comment]
Again, it is MIT licensed so feel free to whatever, including copying and pasting the code if you need to. However, understand that this is not production ready code and that are plenty of algorithms that will outperform it and that contributions regarding packaging are unlikely to be merged upstream.

**Comment by LucBerge** [comment]
Yes. Do you know somd algorirhms on github that could outperform som-tsp ?
