### ISSUE TITLE
Fix x/y ratio into io_helper.py:normalize

### ISSUE THREAD

**Issue by Rouroul** [DiegoVicen/som-tsp#2]
normalize() functions uniformly scales positions 'x' and 'y' columns to a [0,1] range, this transformation doesn't keep the initial map dx/dy ratio and has negative impact on solution.

You can keep the ratio while bounding values to [0,1]:
dx = max(x)-min(x)
dy = max(y)-min(y)
ratio = max(dx, dy)
return (c-c.min()) / ratio

Most of your assets are squares and returns similar results but on assets/qa194.tsp, where dx/dy=1.64, it gives a -7% bonus to total route length.

![som-tsp-perf-scalefix](https://user-images.githubusercontent.com/35929973/35562249-1482de60-05b3-11e8-8ab6-a4c9e8a4ce41.png)

**Comment by DiegoVicen** [comment]
Hm, got to check it out, but you are probably right. If I recall correctly, it should be easy to fix. Thank you for spotting it!
